### PR TITLE
Add: Spanish docs

### PR DESCRIPTION
**Pull request by NikhilKalloli**
Hey @KoljaB, 
Since the project's main goal is to convert text to speech in real time, People from different regions should be able to use it without language barriers.
I've added `spanish` language in the docs so that the documentation is more accessible.
Here are screen shots for your reference:
Screenshot 2024-10-24 170251
Screenshot 2024-10-24 170307

Please review it and let me know the changes.

### CODE REVIEW

**Comment by KoljaB** [comment]
Looks good, thanks a lot

**Comment by NikhilKalloli** [comment]
Hey @KoljaB, Appreciate your response.
Can I add docs in all the languages RealtimeTTS supports ??
This would be a good enhancement for people in different regions and will add more credibility.
Thanks you!

**Comment by KoljaB** [comment]
That would be awesome. Maintenance will be quite hard, but I think it will benefit many people so let's do it.

**Comment by NikhilKalloli** [comment]
Thanks, I already have maintained folder structure for docs. I'll keep it as modular as possible. Will raise a PR soon!

**Pull request merged**
